# format = """
# [](#434C5E)\
# $username\
# [](bg:#4C566A fg:#434C5E)\
# $directory\
# [](fg:#4C566A bg:#5E81AC)\
# $git_branch\
# $git_status\
# [](fg:#5E81AC bg:#2E3440)\
# $character
# """
# format = """
# $username\
# [](white)\
# $directory\
# [](white)\
# $character\
# $git_branch\
# $git_status\
# """

format = """
$character\
$directory\
$git_branch\
$git_status\
"""


# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "white bold"
style_root = "white bold"
format = '[$user ]($style)'

[character]
success_symbol = " [](bold white)"
error_symbol = " [](bold red)"

[directory]
format = "[ $path/ ]($style)"
style = "white"
truncation_length = 1
truncation_symbol = ""

[git_branch]
symbol = ""
format = '[$symbol $branch]($style)'

[git_status]
format = ' [$all_status$ahead_behind]($style) '
